Code Refactoring and Cleanup
rodi0878/NNPTP24-1 pull request #10
Opened 2024-10-13 18:12 UTC by dejv67

This pull request includes a comprehensive refactor of the codebase to improve readability, maintainability, and performance. Unused or redundant code has been removed, naming conventions standardized, and overall code structure simplified without altering functionality.

2024-10-16 08:06 UTC, rodi0878 requested changes
Please review mentioned problematic parts of code

2024-10-16 08:06 UTC, rodi0878 commented on NNPTPZ1/Mathematics/ComplexNumber.cs
> +        public double GetAngleInDegrees()
really?

2024-10-16 08:06 UTC, rodi0878 commented on NNPTPZ1/Mathematics/ComplexNumber.cs
> +        public override bool Equals(object obj)
fix ordering of members in class, group common things together

2024-10-16 21:42 UTC, dejv67 commented
requested changes fixed

2024-10-21 08:21 UTC, rodi0878 commented
ok, accepted

2024-10-21 08:21 UTC, closed without merging