Refaktorizace
rodi0878/NNPTP24-1 pull request #11
Opened 2024-10-14 13:59 UTC by bigibos

Martin Seidl

2024-10-16 08:09 UTC, rodi0878 requested changes
Kód obsahuje příliš nedodělků, je třeba zapracovat další opravy

2024-10-16 08:09 UTC, rodi0878 commented on NNPTPZ1/ComplexNumber.cs
> +        public double GetAngleInDegrees()
skutečně?

2024-10-16 08:09 UTC, rodi0878 commented on NNPTPZ1/ComplexNumber.cs
> +        public double GetAbS()
název

2024-10-16 08:09 UTC, rodi0878 commented on NNPTPZ1/Polynomial.cs
> +            for (int i = 1; i < Coefficients.Count; i++)
proč 1?

2024-10-16 08:09 UTC, rodi0878 commented on NNPTPZ1/Program.cs
> +using System.Diagnostics;
a tyto usingy jsou tu k čemu?

2024-10-16 08:09 UTC, rodi0878 commented on NNPTPZ1/Program.cs
> +            float it = 0;
proč float?

2024-10-16 08:09 UTC, rodi0878 commented on NNPTPZ1/Program.cs
> +            for (int q = 0; q < MaxIterations; q++)
co je q?

2024-10-16 08:09 UTC, rodi0878 commented on NNPTPZ1/Program.cs
> +            var vv = colors[id % colors.Length];
vv?

2024-10-20 08:42 UTC, bigibos commented
Označené části byly upraveny/opraveny.

2024-10-21 08:22 UTC, rodi0878 commented
ok, akceptováno

2024-10-21 08:22 UTC, closed without merging