Refactoring
rodi0878/NNPTP24-1 pull request #17
Opened 2024-11-11 22:16 UTC by CZED0M1

Refaktoring kódu.

Dominik Lopauer

2024-11-14 07:37 UTC, rodi0878 requested changes
Please update code according to mentioned problems, also i dont see definictions of mentioned other classes - ComplexNumber and Polynomial

2024-11-14 07:37 UTC, rodi0878 commented on NNPTPZ1/Program.cs
> +            int[] imagineDimensions = ReadImagineDimensions(args);
please find a better datatype for representing bounds of image

2024-11-14 07:37 UTC, rodi0878 commented on NNPTPZ1/Program.cs
> +                    var color = colors[rootId % colors.Length];
color choosing is very low level in comparison to rest of method

2024-11-14 07:37 UTC, rodi0878 commented on NNPTPZ1/Program.cs
> +            float iterationCount = 0;
why float for count?

2024-11-14 07:37 UTC, rodi0878 commented on NNPTPZ1/Program.cs
> +        private static Polynomial createPolynomial()
broken naming convention

2024-11-18 21:08 UTC, CZED0M1 commented
Dodělány požadované změny.
Dominik Lopauer

2024-11-21 06:06 UTC, rodi0878 commented
accepted

2024-11-21 06:06 UTC, closed without merging