Refactoring
rodi0878/NNPTP24-1 pull request #21
Opened 2024-12-04 09:03 UTC by st64116

Refaktorizace
st64116 - Ondřej Fialka

2024-12-05 08:11 UTC, rodi0878 requested changes
stávající stav je nevyhovující, je potřeba kód dále vylepšit

2024-12-05 08:11 UTC, rodi0878 commented on NNPTPZ1/Mathematics/ComplexNumber.cs
> +        public float Imaginari { get; set; }
proč float? typo v názvu

2024-12-05 08:11 UTC, rodi0878 commented on NNPTPZ1/Mathematics/ComplexNumber.cs
> +        public readonly static ComplexNumber Zero = new ComplexNumber()
pořadí složek ve třídě nedodržuje doporučené konvence

2024-12-05 08:11 UTC, rodi0878 commented on NNPTPZ1/Mathematics/ComplexNumber.cs
> +        public double GetAngleInDegrees()
Skutečně se jendá o stupně?

2024-12-05 08:11 UTC, rodi0878 commented on NNPTPZ1/Mathematics/ComplexNumber.cs
> +        public ComplexNumber Subtract(ComplexNumber b)
b? a?

2024-12-05 08:11 UTC, rodi0878 commented on NNPTPZ1/Program.cs
> +        static void GenerateFractalImage(int width, int height, double xmin, double ymin, double xstep, double ystep, Polynomial p, Polynomial pd, Bitmap bmp)
metoda uvnitř pojímá několik různých úrovní abstrakce, sjednoťte to prosím na jednu úroveň abstrakce, není vhodné kombinovat abstrakce a detaily

2024-12-05 08:11 UTC, rodi0878 commented on NNPTPZ1/Program.cs
> +            for (int q = 0; q < 30; q++)
q?

2024-12-05 08:11 UTC, rodi0878 commented on NNPTPZ1/Program.cs
> +            Color vv = colors[rootIndex % colors.Length];
vv?

2024-12-05 08:11 UTC, rodi0878 commented on NNPTPZ1/Program.cs
> +            vv = Color.FromArgb(vv.R, vv.G, vv.B);
tohle nic nedělá

2024-12-05 20:17 UTC, st64116 commented
Oprava chyb.
Ondřej Fialka

2024-12-09 09:31 UTC, rodi0878 commented
akceptováno

2024-12-09 09:31 UTC, closed without merging