Refactoring kódu
rodi0878/NNPTP24-1 pull request #3
Opened 2024-10-03 09:54 UTC by Palkitch

Autor: Filip Palka

2024-10-05 13:49 UTC, rodi0878 requested changes
Prosím dále zkuste vylepšit označené části

2024-10-05 13:49 UTC, rodi0878 commented on NNPTPZ1/Program.cs
> +			for (int q = 0; q < 30; q++)
proč q? 
co je 30?

2024-10-05 13:49 UTC, rodi0878 commented on NNPTPZ1/Program.cs
> +				if (Math.Pow(diff.RealNumber, 2) + Math.Pow(diff.ImaginaryNumber, 2) >= 0.5)
co je 0.5?

2024-10-05 13:49 UTC, rodi0878 commented on NNPTPZ1/Program.cs
> +			for (int w = 0; w < roots.Count; w++)
w?

2024-10-05 13:49 UTC, rodi0878 commented on NNPTPZ1/Program.cs
> +			var vv = clrs[id % clrs.Length];
pojmenovánoí?

2024-10-05 14:18 UTC, Palkitch commented
Větev "develop" byla změněna dle Vašich požadavků.

2024-10-09 09:18 UTC, rodi0878 commented
akceptováno

2024-10-09 09:18 UTC, closed without merging