Refaktorizace
rodi0878/NNPTP24-1 pull request #5
Opened 2024-10-05 12:04 UTC by Kapicek

Refaktorizace kódu

David Kapeš

2024-10-05 13:54 UTC, rodi0878 requested changes
viz komentáře

2024-10-05 13:54 UTC, rodi0878 commented on NNPTPZ1/ComplexNumber.cs
> +	public class ComplexNumber
ve třídě chybí originální nezbytné API pro další zpracování

2024-10-05 13:54 UTC, rodi0878 commented on NNPTPZ1/Program.cs
> +			for (int iteration = 0; iteration < 30; iteration++)
30? magic number

2024-10-05 13:54 UTC, rodi0878 commented on NNPTPZ1/Program.cs
> +				if (Math.Pow(diff.Real, 2) + Math.Pow(diff.Imaginary, 2) >= 0.5)
0.5?

2024-10-05 13:54 UTC, rodi0878 commented on NNPTPZ1/Program.cs
> +			return Math.Pow(newRoot.Real - knownRoot.Real, 2) + Math.Pow(newRoot.Imaginary - knownRoot.Imaginary, 2) <= 0.01;
0.01?

2024-10-05 14:17 UTC, Kapicek commented
Úprava požadovaných změn

David Kapeš

2024-10-09 09:18 UTC, rodi0878 commented
akceptováno

2024-10-09 09:18 UTC, closed without merging