refactoring
rodi0878/NNPTP24-1 pull request #9
Opened 2024-10-09 19:50 UTC by Axoden

refactoring

Petr Janoušek

2024-10-16 08:04 UTC, rodi0878 requested changes
There are several unfinished problems and also very big bug...

2024-10-16 08:04 UTC, rodi0878 commented on NNPTPZ1/ComplexNumber.cs
> +        public double GetAngleInDegrees()
method name doesnt reflect code

2024-10-16 08:04 UTC, rodi0878 commented on NNPTPZ1/Polynomial.cs
> +        /// Coe
what?

2024-10-16 08:04 UTC, rodi0878 commented on NNPTPZ1/Program.cs
> +            Color vv = CreatePixelColor(it, id);
vv?

2024-10-16 08:04 UTC, rodi0878 commented on NNPTPZ1/Program.cs
> +            float it = 0;
why float?

2024-10-16 08:04 UTC, rodi0878 commented on NNPTPZ1/Program.cs
> +            Color adjustedColor = Color.FromArgb(selectedColor.R, selectedColor.G, selectedColor.B);
useless line

2024-10-16 08:04 UTC, rodi0878 commented on NNPTPZ1/Program.cs
> +            bitmap.SetPixel(j, i, selectedColor);
you seriously messed up whole algorithm - now you use J for the witdth dimension, but before you used it with height in for loop. You need to recheck and fix every match between i,j - witdth,height dimensions

2024-10-16 11:02 UTC, Axoden commented
Changes made on the development branch according to your requests

2024-10-21 08:20 UTC, rodi0878 commented
ok, accepted

2024-10-21 08:20 UTC, closed without merging